### PR TITLE
Histograms For Length of Annotations

### LINKED ISSUE #82: Histogram for length of annotations
Create a new function within  visualizations.py that builds a histogram so that a user can visually see the length of the annotations that they are working with. This would prove to be a very valuable tool in throwing out certain annotations when you are trying to derive relevant statistics for the cross-correlation pipeline.

Matplotlib has a built-in histogram function that can be encapsulated for this task: https://matplotlib.org/stable/gallery/statistics/hist.html

Play around with some data such as the manual labels already on the repository to figure out a reasonable default bin size, but write it in such a way that the user could modify the number of histogram bins. The y-axis should be labeled as "Count" and the x-axis should be labeled as "Annotation Length (s)". The function should accept in a pandas dataframe of annotations, should work with either human annotations or automated annotations. This shouldn't be tricky since they both have the "DURATION" column. Add two extra parameters that give the user the option to download the file.

Call the function annotation_histogram(annotation_df,n_bins = 15, save_fig = False, filename = "annotation_histogram.png")
*n_bins = 15 was an arbitary number I chose, whoever takes this task on, I can send a couple of examples of annotations to get a feel for a number that works decently for all of them.

### PR DESCRIPTION
**Pull request by nishantbalaji**
Closes #82 

* Added `annotation_histograms` function to show a histogram of the lengths of annotations
   * Default number of bins is 10 and max length of clips can be adjusted
   * Not sure if I'm allowed to push the csv files @JacobGlennAyers can you confirm?

Might have to merge linting changes before we merge this one for consistency

### CODE REVIEW

**Review by JacobGlennAyers — CHANGES_REQUESTED** [review]
The formatting on the parameters of each of the functions looks great. 
The formatting on the max and min functions for the lo_idx and hi_idx looks awful. I can review the Steinberg technique and brainsform maybe putting the second parameter of the max and min functions into their own variables, could improve readability. I would approve this commit otherwise.

**Comment by JacobGlennAyers** [comment]
Don't push the csv files, those are restricted to testing.

**Review by JacobGlennAyers — COMMENTED** [review]
The code for generating the local score array plot looks unreadable, particularly the label="_" * ndx + premade_annotations_label) but that may just be an unfortunate garbage code side-effect to get the legend to work in Matplotlib. I have to admit, that I am really not a big fan of this Pep8  putting the parameters of a function that is being called on a separate line. I really want to discuss with the collaborators one more time if this is something that they definitely want. I feel that the changing of the maxval variable in plot_bird_label_scores() is one of the worst offenders.

**Comment by nishantbalaji** [comment]
> The formatting on the parameters of each of the functions looks great.
> The formatting on the max and min functions for the lo_idx and hi_idx looks awful. I can review the Steinberg technique and brainsform maybe putting the second parameter of the max and min functions into their own variables, could improve readability. I would approve this commit otherwise.

> The code for generating the local score array plot looks unreadable, particularly the label="_" * ndx + premade_annotations_label) but that may just be an unfortunate garbage code side-effect to get the legend to work in Matplotlib. I have to admit, that I am really not a big fan of this Pep8 putting the parameters of a function that is being called on a separate line. I really want to discuss with the collaborators one more time if this is something that they definitely want. I feel that the changing of the maxval variable in plot_bird_label_scores() is one of the worst offenders.

I agree that the Pep8 style guidelines make a lot of the code look ugly. This PR doesn't have the full changes, I just rebased with the linting branch so I would avoid merge conflicts. Could you look at #81 for the full PR about linting? I have outlined some changes that need to be made too over there. 

> Don't push the csv files, those are restricted to testing.

Okay, I've deleted them from the PR

**Review by JacobGlennAyers — CHANGES_REQUESTED** [review]
Please push these changes to staging instead of to main.

If you want to show this off, add it to the jupyter notebook tutorial, instead of placing it inside of a new notebook. I think it would fit well after the annotation_duration_statistics() demo.

I think we should go ahead and push the smaller pep8 discrepancies to staging, then handle them with some small tweaks before pushing to main.

The annotation_histogram() function looks great. The code looks very clean, and the parameters are well-defined.

**Comment by nishantbalaji** [comment]
image
Plotted the annotated and manual dataframes

**Pull request closed without merging**
