### PR TITLE
Template Matching and FG-BG Separation

### PR DESCRIPTION
**Pull request by TQZhang04**
Adds functionality for template matching and reverse-engineered BirdNET FG-BG Separation techniques.

### CODE REVIEW

**Review by JacobGlennAyers — COMMENTED** [review]
New documentation looks good, need to double-check the tutorial, which I tend to leave as the Microfaune default

**Comment by JacobGlennAyers** [comment]
@TQZhang04 I think there are only 2 more things to work through here. First, I notice that the demonstrations I had of template matching and foreground-background separation in the tutorial jupyter notebook did carry over, but I would leave the default as Microfaune to keep things consistent. Furthermore, could you maybe discuss with Sean, Sam, and Nathan the nature of all these environment checks with github actions? I think that someone broke the path of the Screaming Piha example dataset that is configured somewhere in github actions. It would be nice if those are all green before we push to main.

**Comment by ntlhui** [comment]
Please update this branch with latest changes from `main` - the environment tests do not need to be run if the `poetry.lock` file has not been modified.

**Review by JacobGlennAyers — APPROVED** [review]
Excellent, I'll go ahead and push the changes to main!

**Pull request merged**
