### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by nishantbalaji**
* updated readme with:
    * per function documentation
    * how to use
    * examples

### CODE REVIEW

**Review by JacobGlennAyers — CHANGES_REQUESTED** [review]
Create a pull request from the readme branch to the staging branch instead of directly to main. Since I commit a bunch of changes related to the organization of the new test set as well as updated the Jupyter notebook tutorial. I think I want to have a person or two test out our instructions that haven't played around with PyHa that much before we commit the readme to main.

**Comment by JacobGlennAyers** [comment]
This has to be updated with the more recent screaming piha dattaset. Specifically, the generate_automated_labels() output will be completely different as well as all of the dataset-wide statistics since they are being generated from different audio clips.

**Comment by JacobGlennAyers** [comment]
You can find the new labels in the link from my commit to the readme branch in the setup steps. They can also be found in the staging branch where they are already committed. It is just that the images in the readme need to be updated with the new numbers. You can take screenshots from the staging jupyter notebook tutorial that is up to date.

**Comment by nishantbalaji** [comment]
> You can find the new labels in the link from my commit to the readme branch in the setup steps. They can also be found in the staging branch where they are already committed. It is just that the images in the readme need to be updated with the new numbers. You can take screenshots from the staging jupyter notebook tutorial that is up to date.

@JacobGlennAyers Images have been updated, please let me know if I missed any

**Comment by JacobGlennAyers** [comment]
It seems that I didn't update my local repository properly before pushing some changes to fix some linting errors. I did a force push and it seems to have deleted the changes when I merged this PR request. Luckily this is the only commit to have happened. I want to make sure you get credit for the readme work and everything, so go ahead and submit a new PR request and i will get my local branch up to date and push the small linting changes properly on my end.

**Pull request merged**
