### PR TITLE
Ctrl c exception handling

### PR DESCRIPTION
**Pull request by JacobGlennAyers**
Added in more predictable behavior when processing large datasets, allowing a user to stop the process via Ctrl-C

### CODE REVIEW

**Comment by sprestrelski** [comment]
Both the system exits work for Microfaune and TweetyNet! Would you be able to implement this functionality for BirdNET as well? You may need to look into the birdnet_lite/analyze.py script as interrupting from `generate_automated_labels` may not stop the process. I would check out what the behavior currently looks like when trying (and failing) a KeyboardInterrupt, then tracing where the error message comes from.

**Review by sprestrelski — CHANGES_REQUESTED** [review]
Both the system exits work for Microfaune and TweetyNet! Would you be able to implement this functionality for BirdNET as well? You may need to look into the birdnet_lite/analyze.py script as interrupting from `generate_automated_labels` may not stop the process. I would check out what the behavior currently looks like when trying (and failing) a KeyboardInterrupt, then tracing where the error message comes from.

**Review by purovida94 — COMMENTED** [review]
@sprestrelski I added in some KeyboardInterrupt exceptions in to analyze.py. they're working on my end, let me know if they're working for you too. Gracias!

**Review by sprestrelski — APPROVED** [review]
Looks good on my end 🤠

**Review by purovida94 — APPROVED** [review]

**Comment by JacobGlennAyers** [comment]
Merged, thanks Teo!

**Pull request merged**
