### PR TITLE
Generalizing file types

### LINKED ISSUE #7: Make the pipeline more generalizable beyond .wav files.
Might want to consider refactoring with Librosa since their code is more generalizable than scipy's wavfile.read(). 

Unfortunately with the current demo work that we have, they use wavfile.read() in their wrapper function audio.load_wav(). So whoever takes this task needs to test and compare their solution to the outputs of the same files in different formats. 

I did a little work related to mp3's back in the day.
https://github.com/UCSD-E4E/passive-acoustic-biodiversity/blob/master/mp3_to_wav/Conversion.ipynb

Just try to get different audio data types down to numpy arrays is the name of the game.

### PR DESCRIPTION
**Pull request by pranjalc1**
Closes #7 

Allows to use various file types (such as mp3 and flac files), instead of just wav files

### CODE REVIEW

**Review by sprestrelski — CHANGES_REQUESTED** [review]
Looks great! Thanks for adding the documentation on the signal scaling, very informative Just a few general bookkeeping things I noticed:
1. Please update the other environment files in the conda_environments folder with the newly added dependencies (e.g. torchaudio)
2. In generate_automated_labels_microfaune(), we'd actually like to keep the weight_path functionality to load in custom weights. Is there a different way to handle a "model does not exist" case while keeping that functionality?

**Comment by pranjalc1** [comment]
Hello! Thank you for checking the pull request.

1. I actually think the new dependencies were not used, so I will just delete the environment file (I did not use torchaudio, only librosa, which had already been added onto the previous environments).
2. I am not sure how the code for the RNN detector got deleted (maybe something in the rebasing), but I added the code back in above.

**Review by sprestrelski — APPROVED** [review]
Thanks for the update! I'll add testing and merging this to my list of tasks for this week.

**Comment by sprestrelski** [comment]
#132 If mp3 files don't work, ffmpeg is probably the missing dependency

**Pull request merged**
