### PR TITLE
Label chunker

### PR DESCRIPTION
**Pull request by JacobGlennAyers**
This PR request is to make sure the technology is available for tweetynet outputs to be modified in the format of a chunk isolation technique, I.E. for our needs to be uniform 3s segments.

### CODE REVIEW

**Review by mugen13lue — COMMENTED** [review]
I will test this with tweetynet, but so far looks good.

**Review by shreyasar2202 — APPROVED** [review]
It seems to work fine when I checked

**Comment by Sean1572** [comment]
> I will test this with tweetynet, but so far looks good.

Tweetynet is working with label chunker output

**Review by Sean1572 — APPROVED** [review]
Tested label_chunker with TweetyNet with all 3 techniques and it's own raw output, BirdNET under Steinburg, and Mircofaune. All worked as expected.

**Review by sprestrelski — APPROVED** [review]

**Pull request merged**
