### PR TITLE
Birdnet integration

### PR DESCRIPTION
**Pull request by JacobGlennAyers**

### CODE REVIEW

**Comment by sprestrelski** [comment]
Found a bug in how the automated_df parameter was typechecked. Everything else worked fine. Further RIP to Normalized_Sample_Rate 😊

**Review by sprestrelski — COMMENTED** [review]
Found a bug in how the automated_df parameter was typechecked. Everything else worked fine. Further RIP to Normalized_Sample_Rate 😊

**Review by shreyasar2202 — COMMENTED** [review]
There are a couple of things that I noticed
1. The BirdNet README needs to be updated with the new argument that we added.
2. The color codes look confusing for this cell when using BirdNet isolation parameters
image
The markdown cell mentions white for true negatives, but the spectrogram shows blue

Apart from these, the changes look good to me!

**Comment by JacobGlennAyers** [comment]
Shreyas, when you say argument added, which function are you referring to?

**Comment by shreyasar2202** [comment]
> Shreyas, when you say argument added, which function are you referring to?

I am referring to the 'num_predictions' command line argument

**Comment by JacobGlennAyers** [comment]
> > Shreyas, when you say argument added, which function are you referring to?
> 
> I am referring to the 'num_predictions' command line argument

Cool, just changed our repo

**Pull request merged**
